# Generated by Django 5.2.4 on 2025-09-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
