# Generated by Django 5.2.4 on 2025-09-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_orden_segundo_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
