# Generated by Django 5.2.4 on 2025-09-21 09:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupones', '0001_initial'),
        ('ordenes', '0003_orden_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='cupones.cupon'),
        ),
        migrations.AddField(
            model_name='orden',
            name='descuento',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
