# Generated by Django 5.2.4 on 2025-10-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_cuenta',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('personal', 'Personal')], default='cliente', max_length=20),
        ),
    ]
