# Generated by Django 5.2.4 on 2025-10-11 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_usuario_tipo_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionesUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metricas_activas', models.JSONField(default=dict, help_text='Diccionario con las métricas activas en el dashboard.')),
                ('tema', models.CharField(choices=[('claro', 'Modo claro'), ('oscuro', 'Modo oscuro')], default='claro', max_length=20)),
                ('mostrar_tendencias', models.BooleanField(default=True, help_text='Indica si se visualizan los gráficos de tendencia.')),
                ('mostrar_alertas', models.BooleanField(default=True, help_text='Mostrar alertas de stock y rendimiento automáticamente')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de usuario',
                'verbose_name_plural': 'Configuraciones de usuarios',
            },
        ),
    ]
