# Generated by Django 5.2.4 on 2025-10-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_configuracionesusuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfiguracionesUsuario',
            new_name='ConfiguracionUsuario',
        ),
    ]
