# Generated by Django 5.2.4 on 2025-10-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_rename_configuracionesusuario_configuracionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='preferencias',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
