# Generated by Django 5.2.4 on 2025-10-08 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre_empresa')),
                ('cif', models.CharField(max_length=20, unique=True, verbose_name='CIF')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento')),
                ('iva', models.DecimalField(decimal_places=2, default=21.0, max_digits=2, verbose_name='IVA')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock disponible'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=10, verbose_name='Stock Mínimo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tienda.proveedor', verbose_name='Proveedor'),
            preserve_default=False,
        ),
    ]
