# Generated by Django 5.2.4 on 2025-10-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_proveedor_producto_stock_producto_stock_minimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='descuento',
            field=models.FloatField(default=0.0, verbose_name='Descuento (%)'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='iva',
            field=models.FloatField(default=21.0, verbose_name='IVA (%)'),
        ),
    ]
