"""
Django settings for compushop project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config  # No Aparece por defecto.
import os  # No Aparece por defecto.
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sfr7-be7+fd=ch%ajr@a%g6ei*rj7b*n3xpx#hnpe7!pb_%_lx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'carro.apps.CarroConfig',
    'ordenes.apps.OrdenesConfig',
    'cuentas.apps.CuentasConfig',
    'pagos.apps.PagosConfig',
    'tienda.apps.TiendaConfig',
    'cupones.apps.CuponesConfig',
    'rosetta',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # No Aparece por defecto.
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

ROOT_URLCONF = 'compushop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',  # No Aparece por defecto.
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'carro.context_processors.carro',  # No Aparece por defecto.
                'tienda.context_processors.categorias_disponibles',  # No Aparece por defecto.
            ],
        },
    },
]

WSGI_APPLICATION = 'compushop.wsgi.application'

ID_SESSION_CARRO = 'carro' # No Aparece por defecto.


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Ususario personalizado.
AUTH_USER_MODEL = 'cuentas.Usuario'
LOGIN_REDIRECT_URL = 'cuentas:panel_personal'
LOGOUT_REDIRECT_URL = 'tienda:listado_productos'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'
USE_I18N = True
LANGUAGES = [
    ('es', 'Español'),
    ('en', 'Inglés'),
]
# LOCALE_PATHS especifica donde django busca archivos para las taducciones.
LOCALE_PATHS = [       # No Aparece por defecto.
    os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = 'UTC'

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'  # No Aparece por defecto.
STATICFILES_DIRS = [ BASE_DIR / "staticfiles" ]  # No Aparece por defecto.

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'   # No Aparece por defecto.
MEDIA_ROOT = BASE_DIR / 'media'   # No Aparece por defecto.
TIME_ZONE = 'Europe/Madrid'   # No Aparece por defecto.

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'   # No Aparece por defecto.

CELERY_BROKER_URL = 'amqp://localhost'   # No Aparece por defecto.

# Stripe settings
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY')   # No Aparece por defecto.
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')   # No Aparece por defecto.
STRIPE_API_VERSION = '2024-04-10'   # No Aparece por defecto.
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET')   # No Aparece por defecto.

# Redis settings
REDIS_HOST = 'localhost'   # No Aparece por defecto.
REDIS_PORT = 6379   # No Aparece por defecto.
REDIS_DB = 1   # No Aparece por defecto.
